

CXXFLAGS += -I../include -I../../pnifixedpoint/include -std=c++11 -g

SRCS += ../../pnifixedpoint/pnifixedpoint.cpp
SRCS += ../pnicolor.cpp
SRCS += pnicolor-test.cpp

pnicolor-test: $(SRCS)

clean:
	rm pnicolor-test

.PHONY: clean
