

CXXFLAGS += -I../include -std=c++11 -g
CXXFLAGS += -Wno-unknown-pragmas

SRCS += ../pnifixedpoint.cpp
SRCS += pnifixedpoint-test.cpp

pnifixedpoint-test: $(SRCS)

clean:
	rm pnifixedpoint-test

.PHONY: clean
